name: Build wheels (uv)


# for now: runs only on manual trigger
on:
  workflow_dispatch:

#on:
#  push:
#    branches: ["main"]
#    tags: ["v*"]
#  pull_request:


permissions:
  contents: read

jobs:
  build:
    name: Build on ${{ matrix.os }} / py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Build wheel + sdist
        run: |
          uv build --wheel --sdist
        # Output goes to ./dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.os }}-py${{ matrix.python }}
          path: dist/*
          if-no-files-found: error
          retention-days: 30

  release:
    name: Create GitHub Release and upload wheels
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

